name: CI_PYTHON_TEST
on: workflow_dispatch

jobs:
  CI_PYTHON_TEST:
    runs-on: ubuntu-latest
    steps:
    
      - name: Pre checkout
        run: |
          pwd
          ls -lh
          
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: After checkout
        run: |
          pwd
          ls -lh
          
      - name: Install pytest
        run: pip install pytest
        
      - name: Print secret environment variable
        run: |
          echo "My secret is: ${{ secrets.Testing }}" # Replace MY_SECRET with your secret's name
          
      - name: Run pytest
        run: pytest

        
