name: CI_PYTHON_TEST
on: workflow_dispatch

jobs:

  CI_PYTHON_TEST:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        run: |
          git clone https://github.com/lamsiufung/github-action-1
          cd github-action-1
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest

        
