name: CI_PYTHON_TEST
on: workflow_dispatch

jobs:
  CI_PYTHON_TEST:
    runs-on: ubuntu-latest
    steps:
    
      - name: pre checkout
        run: |
          pwd
          ls -lh
          
      - name: checkout repository
        uses: actions/checkout@v4
        
      - name: after checkout
        run: |
          pwd
          ls -lh
          
      - name: install pytest
        run: pip install pytest
        
      - name: run pytest
        run: pytest

        
