name: CI

on: workflow_dispatch

jobs:
  build_test_on:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          date1
          
  build_test_on_windows:
    runs-on: windows-latest
    if: ${{ success() }}
    needs: [build_test_on]
    steps:
      - name: Run a mult-line script
        run: |
          echo "hello github actions!"
          echo "i am using the windows runner!"
          date
        
